### PR TITLE
Add MLSys 2019, MLSys 2020

### PR DESCRIPTION
**Pull request by ssheikholeslami**

### CODE REVIEW

**Comment by ssheikholeslami** [comment]
Hi, first of all, great job!
I think the contribution guide can be improved a bit:

- you can add a step for making sure the .bib is removed (didn't do it my PR though, since it was not stated)
- adding a step to update the README.md with appropriate changes to the list of conferences

Also, there is a bit of inconsistency in the JSON filenames in the `data` folder - I think the JSON files originating from your own commits have the `*.bib.json` suffix, but the guide asks for `*.json`. This might lead to some confusion.

**Comment by yuchenlin** [comment]
Thank you very much @ssheikholeslami ! These are very great suggestions and I will improve the instruction asap!

**Comment by yuchenlin** [comment]
Hi @ssheikholeslami , the current readme is confusing. The correct bib of a conference is like the list of the bibtex entries of all the papers in that proceedings.
On DBLP, you can get this by  go to here https://dblp.org/db/conf/mlsys/mlsys2020.html and 
image

**Comment by yuchenlin** [comment]
In case you wonder how to get the URL of this page:
We need to first click the "contents" button in this page https://dblp.org/db/conf/mlsys/index.html
image

**Comment by yuchenlin** [comment]
(I know this is tiring and I feel like there must be an easier way to do this by DBLP's API, but I am having some urgent deadlines lately. Will check later.)

**Comment by ssheikholeslami** [comment]
Oh, my bad - no wonder the file size was so small :D

**Pull request merged**
